Traceback (most recent call last):
  File "/home/vitran/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "/home/vitran/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'tv_weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_sim.py", line 463, in <module>
    tv_weight = wandb.config.tv_weight
  File "/home/vitran/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 169, in __getattr__
    ) from ke
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'tv_weight'
